version: 2

workflows:
  version: 2
  #  normal_build_and_test:
  #    jobs:
  #    - build_and_test

  release:
    jobs:
      - release:
          context: xtrabackup-build
          filters:
            tags:
              only:
                - "/.*/"
            branches:
              ignore: /.*/

jobs:
  release:
    environment:
      CI: "true"
      BUILDKIT_PROGRESS: plain
    # Builds on arm64
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
#      - restore_cache:
#          keys:
#            - xtrabackup-v1
      - run: ./.circleci/linux_circle_vm_setup.sh
      - run: cd xtrabackup-8.0 >/dev/null && ./build.sh
#      - save_cache:
#          key: xtrabackup-v1
#          paths:
#            - xtrabackup-8.0/percona-xtrabackup
      - run:
          name: Upload artifacts to GitHub release page
          command: |
            if [ ! -z "${GTOKEN}" ]; then
              echo "GTOKEN provided, pushing release ${CIRCLE_TAG}"
              echo ${GTOKEN} | gh auth login --with-token
              gh release upload --clobber ${CIRCLE_TAG} xtrabackup-8.0/install/xtrabackup-*tar.gz*
              echo | gh auth logout --hostname=github.com
            else
             echo "GTOKEN not provided, not pushing release $CIRCLE_TAG"
            fi
